version: '3.5'
services:
  mongodb:
    image: mongo:4.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    networks:
      - mongodb-network
    volumes:
      - mdb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on: 
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
    networks: 
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge

volumes:
  mdb-data:
